@startuml

' === Style Tweaks ===

skinparam {
  Style StrictUML
  RoundCorner 5
  ParticipantPadding 10
  Padding 2
  SequenceStereotype {
    Font {
      Size 11
      Style plain
    }
  }
  Database {
    BorderColor #A80036
  }
}


' === Actors / Participants

actor "User" as user
participant "Home Page" as homePage << JSP Page >>
participant "CreateAccountServlet" as createServlet <<Servlet>>
participant "create-account-details" as createPage << JSP Page >>
participant "Session" as session
participant "CustomerJdbiDAO" as dao << DAO >>
database "Database" as db


' === Interactions ===


user -> homePage++ : clicks "Create Account" button
homePage -> createPage--++ : Redirect to create account
' createServlet -> createPage++ : Render create account page
createPage --> user-- : Display create account form
user -> createPage++ : Enters account details
createPage --> createServlet--++ : Submits account details



alt Customer already exists
  createServlet -> dao++ : doPost

     dao --> db--++ : dao.save(customer)
  db --> createPage-- : Exception caught/ User already exists
else Customer created successfully
    createServlet -> dao++ : doPost 
    dao --> db : dao.save(customer)
 

  db -->  dao : result
  dao --> createServlet : Insert succeeds
    end

  dao--
  createServlet -> session++ : setAttribute("customer", customer)
   
  session -> homePage++ : Customemised home page



    

' createPage -> session++ : setAttribute("customer", customer)


' createServlet -> dao++ : postById(id)
' dao -> db++ : insert into Customer(values)

' return result
' return Customer

' createServlet -> session++ : setAttribute("customer", customer)
' createServlet -> createPage++ : redirect

' createPage -> session++ : getAttribute("customer")
' return student

' createPage -> createPage : add student\ndetails to form

' createPage -->user : student details ready to update

@enduml
