@startuml

' === Style Tweaks ===

skinparam {
  Style StrictUML
  RoundCorner 5
  ParticipantPadding 10
  Padding 2
  SequenceStereotype {
    Font {
      Size 11
      Style plain
    }
  }
  Database {
    BorderColor #A80036
  }
}


' === Actors / Participants

actor "User" as user
participant "View Products\nPage" as viewPage << JSP Page >>
participant "Session" as session
participant "CustomerJdbiDAO" as dao << DAO >>
database "Database" as db

user --> viewPage: Clicks "View Products"
viewPage -> session: Get session
session -> dao: Get all products
dao -> db: SELECT * FROM products
db --> dao: ResultSet
dao --> session: List<Product>
session --> viewPage: List<Product>
viewPage --> user: Display products

  





' === Interactions ===





@enduml
